### ISSUE TITLE
Sequelize初始化时应该设置时区

### ISSUE THREAD

**Issue by abc1747232439** [qiheizhiya/myBlog#6]
若不设置时区，使用其提供的timestamps，会导致比当前时间慢八个小时
`module.exports = {
    localDb:{
        database:"blog_test1",  /* 本地 */
        username:"root",
        password:"wzj12345",
        host:{
            host:"localhost",
            dialect:"mysql",
            timezone: '+08:00' //东八时区
        }
    },`
比如在16：59分左右创建一个账号
数据库中却显示的时间却是7：59
而在浏览器localstroage存储的createdAt却是正常时间

**Comment by xiaojieajie** [comment]
Thanks to add
